version: '3'

services:
    web:
        image: nginx
        ports:
            - '8000:80'
        depends_on:
            - app
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    app:
        build: ./docker/php
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: XXXX
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql 

